idf_component_register(
    SRCS
        "main.cpp"
        "sensors.cpp"
        "display.cpp"
        "input.cpp"
        "alarm.cpp"
        "motion.cpp"
        "system_state.cpp"
        "rtos_objects.cpp"
        "system_tasks.cpp"
    INCLUDE_DIRS
        "../include"
    REQUIRES
        driver
    PRIV_REQUIRES
        freertos
)
